In [2]:
import numpy as np

In [3]:
#  np.abs?  可以查看帮助文档
#  np.+TAB按键，查看可以使用的函数

## 数组生成

In [8]:
# 从python的基础数据类型创建数组

list1 = [9, 6, 2, 4, 9, 9]
nd1 = np.array(list1)
print(nd1)
print(type(nd1))

list2 = [[9, 6, 2], [4, 9, 9]]
nd2 = np.array(list2)
print(nd2)
print(type(nd2))

[9 6 2 4 9 9]
<class 'numpy.ndarray'>
[[9 6 2]
 [4 9 9]]
<class 'numpy.ndarray'>


In [10]:
# 利用random模块生成数组

- random 0到1随机数
- uniform 均匀分布随机数
- randn 标准正态随机数
- randint 随机整数
- normal 正态分布
- shuffle 随机打乱
- seed 设置随机数种子

In [13]:
nd3 = np.random.random([3,3])
print(nd3)

[[0.66972145 0.08162381 0.45570004]
 [0.36790888 0.13168312 0.49624379]
 [0.80877695 0.53779159 0.10276517]]


In [15]:
np.random.seed(123)
nd4 = np.random.randn(2,3)
print(nd4)
np.random.shuffle(nd4)
print(nd4)

[[-1.0856306   0.99734545  0.2829785 ]
 [-1.50629471 -0.57860025  1.65143654]]
[[-1.50629471 -0.57860025  1.65143654]
 [-1.0856306   0.99734545  0.2829785 ]]


In [16]:
# 创建特定形状的多维数组

- np.zeros：全为0数组
- np.ones：全为1数组
- np.empty: 空数组
- np.zeros_like(ndarr):以ndarr相同维度创建全0数组
- 同 empty; ones

In [20]:
# 利用arange;linspace生成数组
print(np.arange(10))
print(np.arange(0,10))
print(np.arange(1, 4, 0.5))
print(np.arange(9, -1, -1))

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[1.  1.5 2.  2.5 3.  3.5]
[9 8 7 6 5 4 3 2 1 0]


In [24]:
# linspace函数包含起点和终点
print(np.linspace(0,10,11))
print(np.linspace(0,10,10))

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


## 获取元素

In [34]:
np.random.seed(2019)
q = np.random.random(10)
q

array([0.90348221, 0.39308051, 0.62396996, 0.6378774 , 0.88049907,
       0.29917202, 0.70219827, 0.90320616, 0.88138193, 0.4057498 ])

In [35]:
# 获取指定位置元素(获取第四个元素)
q[3]

0.6378774010222266

In [36]:
# 截取一段数据
q[3:6]

array([0.6378774 , 0.88049907, 0.29917202])

In [37]:
# 截取固定间隔数据
q[1:6:2]

array([0.39308051, 0.6378774 , 0.29917202])

In [38]:
# 倒序取数
q[::-2]

array([0.4057498 , 0.90320616, 0.29917202, 0.6378774 , 0.39308051])

In [41]:
qq = np.arange(25).reshape(5,5)

In [42]:
qq

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [44]:
# 截取多维数组某一区域数据
qq[1:3,1:3]

array([[ 6,  7],
       [11, 12]])

In [45]:
# 截取多维数组数值在一个值域内数据
qq[(qq>3)&(qq<10)]

array([4, 5, 6, 7, 8, 9])

In [48]:
# 截取多维数组中指定的行
qq[1:3, :]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [49]:
# 截取多维数组中指定的列
qq[:, 1:3]

array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17],
       [21, 22]])

In [50]:
qq[2::2,::2]

array([[10, 12, 14],
       [20, 22, 24]])

## 算术运算

In [52]:
# 对应元素相乘
# 注意是对应元素相乘,而不是正常的矩阵运算
A = np.array([[1,2],[3,4]])
B = np.array([[1,2],[0,0]])
A*B

array([[1, 4],
       [0, 0]])

In [53]:
# 内积
np.dot(A,B)

array([[1, 2],
       [3, 6]])

## 数组变形

In [1]:
# reshape : 改变向量的维度，不修改向量本身
# 指定维度时可以只指定行数或者列数，其他用-1代替

# resize ： 改变向量的维度，修改向量本身

# ravel ： 向量展平
# rabel('F') : 按照列优先，展平
# ravel() : 按照行优先，展平

# flatten ：将矩阵转换为向量

# squeeze ： 把矩阵中含1的维度去掉

# transpose ：对高维矩阵进行轴对换

## 数组变形

In [3]:
# append : 合并一维数组
# np.append(a, b, axis = 0) 按照行合并
# np.append(a, b, axis = 1) 按照列合并

# concatenate 沿指定轴连接数组或矩阵

# stack 沿指定轴堆叠数组或矩阵

## 批量处理

In [9]:
data_train = np.random.randn(10000, 2, 3)
print(data_train.shape)

(10000, 2, 3)


In [10]:
np.random.shuffle(data_train)
batch_size = 100
for i in range(0, len(data_train), batch_size):
    x_batch_sum = np.sum(data_train[i:i+batch_size])
    print("第{}批次，该批次数据和{}".format(i, x_batch_sum))

第0批次，该批次数据和34.74436557751068
第100批次，该批次数据和5.240833572557508
第200批次，该批次数据和22.80298861625309
第300批次，该批次数据和15.68120562640147
第400批次，该批次数据和2.7222156478707618
第500批次，该批次数据和-2.5220903256034024
第600批次，该批次数据和35.11572410814219
第700批次，该批次数据和1.0235197071987283
第800批次，该批次数据和-5.961463554853683
第900批次，该批次数据和1.3483880291262214
第1000批次，该批次数据和-3.5930603850759164
第1100批次，该批次数据和0.7653515737129091
第1200批次，该批次数据和14.56468229642674
第1300批次，该批次数据和34.06707414342066
第1400批次，该批次数据和-16.854216491245644
第1500批次，该批次数据和16.022981819700036
第1600批次，该批次数据和18.211866034104823
第1700批次，该批次数据和14.810920169045723
第1800批次，该批次数据和38.65993454869405
第1900批次，该批次数据和13.426825594656478
第2000批次，该批次数据和9.170232509794078
第2100批次，该批次数据和6.1360304827707495
第2200批次，该批次数据和6.764444057691147
第2300批次，该批次数据和5.923675266632911
第2400批次，该批次数据和-20.537519995245148
第2500批次，该批次数据和-2.4329634617832347
第2600批次，该批次数据和-3.90799328293377
第2700批次，该批次数据和0.5776861519293757
第2800批次，该批次数据和25.474639453190775
第2900批次，该批次数据和51.849781305250254
第3000批次，该批次数据和-12.85233344802

## 通用函数
- 比math处理速度更快

In [11]:
# sqrt;sin;cos;;abs;dot;log;log10;log2;exp;cuncom(累计求和);cumproduct(累计求积);sun;mean;median;std;var;corrcoef